name: Deploy
on: push

jobs:  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Copy the files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: 13.201.101.208
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'build/*'
          target: '/var/www/html/'

      - name: Restart Apache server
        run: ssh ubuntu@13.201.101.208 "sudo systemctl restart apache2"
